name: ARM Manifest Canary Release $(rev:r)
trigger: none
parameters:
  - name: ArtifactBranch
    type: string
    default: "manifest"
  - name: "Environment"
    displayName: "Environment to use"
    type: string
    default: Production
variables:
  - name: CommitId
    value: abc
  - name: HasNewResourceType
    value: false
resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
  builds:
    - build: ArmManifest
      type: CloudVaultArtifacts-v3
      branch: git_mgmt_recoverysvcs_regionalrp_${{parameters.ArtifactBranch}}
      connection: CloudVault API - AzureBuilds
      source: fb10185a-465d-42cd-b339-7d0d9331c340
extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    stages:
      - stage: Prod__ARM_Manifest
        displayName: "Prod: ARM Manifest"
        variables:
          - name: ob_release_environment
            value: ${{parameters.Environment}}
        dependsOn: []
        jobs:
          - job: ppe__arm_manifest_agent_job
            displayName: Agent job
            pool:
              type: release
            steps:
              - downloadBuild: ArmManifest
              - task: vsrm-ev2.vss-services-ev2.adm-release-task.ExpressV2Internal@1
                inputs:
                  UseServerMonitorTask: true
                  EnableStrictValidation: false
                  ValidateOnly: false
                  EndpointProviderType: ApprovalService
                  ServiceRootLocation: LinkedArtifact
                  RolloutSpecType: RSPath
                  ServiceRootPath: $(Pipeline.Workspace)/ArmManifest/retail-amd64/ARMManifests/Canary/Microsoft.RecoveryServices_RA
                  RolloutSpecPath: $(Pipeline.Workspace)/ArmManifest/retail-amd64/ARMManifests/Canary/Microsoft.RecoveryServices_RA/RolloutSpec.json
                  Select: regions(*)
                  ConfigurationOverrides: |
                    {
                      "$schema": "https://ev2schema.azure.net/schemas/2020-04-01/ConfigurationOverrides.json",
                      "ConfigurationSpecification": {
                        "Settings": {
                          "CanaryRegion": "brazilus",
                          "HasNewResourceType": "false"
                        }
                      }
                    }
                  ApprovalServiceEnvironment: ${{parameters.Environment}}
